version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo "Building the Remote Executor distribution..."
      - chmod +x ./gradlew
      - ./gradlew :executor:distTar
  post_build:
    commands:
      - echo "Uploading artifact to the environment-specific S3 Bucket..."
      - aws s3 cp executor/build/distributions/executor.tar s3://$ARTIFACT_BUCKET/remote-executor/executor.tar

      - echo "Triggering EC2 Image Builder Pipeline..."
      - aws imagebuilder start-image-pipeline-execution --image-pipeline-arn $PIPELINE_ARN
