AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB tables for Remote Executor'

Resources:
  JobStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RemoteExecutor-JobState
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: JobId
          AttributeType: S
        - AttributeName: InstanceId
          AttributeType: S
        - AttributeName: JobState
          AttributeType: S
      KeySchema:
        - AttributeName: JobId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ActiveInstancesIndex
          KeySchema:
            - AttributeName: InstanceId
              KeyType: HASH
            - AttributeName: JobState
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY

Outputs:
  JobStateTableArn:
    Value: !GetAtt JobStateTable.Arn
